telegram:
  token: "123456789:ABCdefGHIjklmNOPQrsTUVwxyz_FAKE_TOKEN"
  chat_id: "987654321"

scanner:
  timeout: 2
  max_threads: 500

portscan:
  target: "scanme.nmap.org"
  startport: 1
  endport: 1025

dirscan:
  wordlist: "./wordlists/common.txt"