telegram:
  token: "TOKEN"
  chat_id: "CHAT_ID"

scanner:
  timeout: 1
  max_threads: 100

portscan:
  target: "scanme.nmap.org"
  startport: 1
  endport: 1025

dirscan:
  wordlist: "./wordlists/common.txt"